### ISSUE TITLE
webrtc custom header are not forwared to remote host 

### ISSUE THREAD

**Issue by vdharashive** [drachtio/drachtio-rtpengine-webrtcproxy#24]
the custom header  not forwarded to the destination host 

below headers is invite from webrtc 

NVITE sip:st-56b68aad-4523-58f6-a634-36220b4c564f@sbc2-xxxx-np.xxxx.ai SIP/2.0
Via: SIP/2.0/WSS kgny60o89agb.invalid;branch=z9hG4bK1592261
Max-Forwards: 69
To: <sip:st-56b68aad-4523-58f6-a634-36220b4c564f@sbc2-xxxx-np.xxxx.ai>
From: "u-226173bb-6084-5be7-9178-bdb72da88ae8" <sip:u-226173bb-6084-5be7-9178-bdb72da88ae8@sbc2-xxxx-np.xxxx.ai>;tag=nt09nbqvrk
Call-ID: h2u9ka02rhqi3foqm1t6
CSeq: 7850 INVITE
X-PHONE-NUMBER:
X-botName: null
X-Call-ID: null
X-CALLFLOW-ID: cf-afb6f91a-476a-597a-a320-62415eb5e68b
X-CALLFLOW-STATE: configured
Contact: <sip:u-226173bb-6084-5be7-9178-bdb72da88ae8@kgny60o89agb.invalid;transport=ws;ob>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY,SUBSCRIBE
Supported: ice,replaces,outbound
User-Agent: JsSIP 3.9.0
Content-Length: 2097

v=0
o=- 8798285559915109936 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS 997b018b-70dc-461f-bed3-2f7ed64e2518
m=audio 36254 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 52.66.194.15
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2427650891 1 udp 2122260223 172.16.3.148 57548 typ host generation 0 network-id 1 network-cost 10
a=candidate:1269834506 1 udp 1686052607 115.114.88.222 57548 typ srflx raddr 172.16.3.148 rport 57548 generation 0 network-id 1 network-cost 10
a=candidate:4001161683 1 tcp 1518280447 172.16.3.148 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=candidate:3703376948 1 udp 41886207 52.66.194.15 36254 typ relay raddr 115.114.88.222 rport 57548 generation 0 network-id 1 network-cost 10
a=candidate:2725441196 1 udp 25108479 52.66.194.15 25601 typ relay raddr 115.114.88.222 rport 33042 generation 0 network-id 1 network-cost 10
a=candidate:2725441196 1 udp 25108735 52.66.194.15 48915 typ relay raddr 115.114.88.222 rport 33546 generation 0 network-id 1 network-cost 10
a=ice-ufrag:LeEw
a=ice-pwd:Uf+Q78tcTtCl+i+Df9rft4Pz
a=ice-options:trickle
a=fingerprint:sha-256 BB:19:80:72:60:10:3D:33:4E:74:F9:A4:3F:21:55:FD:A5:E0:70:B4:CB:2A:21:E3:E5:94:DB:15:F9:65:E8:61
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:997b018b-70dc-461f-bed3-2f7ed64e2518 a68a4749-db42-4ea0-b1ec-81e88033bbfd
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:3856066122 cname:IX51hRpoHTu9FFR0
a=ssrc:3856066122 msid:997b018b-70dc-461f-bed3-2f7ed64e2518 a68a4749-db42-4ea0-b1ec-81e88033bbfd\

forwarded packet 

2024/03/07 14:03:06.740284 172.31.11.64:9090 -> x.x.x.x.x:5060
INVITE sip:st-56b68aad-4523-58f6-a634-36220b4c564f@sbc2-xxxx-np.xxxx.ai SIP/2.0
Via: SIP/2.0/UDP 3.225.113.125:9090;rport;branch=z9hG4bKeX5vKjBm4FNZa
Max-Forwards: 70
From: "u-226173bb-6084-5be7-9178-bdb72da88ae8" <sip:u-226173bb-6084-5be7-9178-bdb72da88ae8@sbc2-korevg-np.kore.ai>;tag=4d7gn079r8
To: <sip:st-56b68aad-4523-58f6-a634-36220b4c564f@sbc2-korevg-np.kore.ai>
Call-ID: 437a394a-572e-123d-4fac-02159e8c174f
CSeq: 1 INVITE
Contact: <sip:3.225.113.125:9090>
User-Agent: JsSIP 3.9.0
Allow: INVITE, ACK, CANCEL, BYE, UPDATE, MESSAGE, OPTIONS, REFER, INFO, NOTIFY, SUBSCRIBE
Supported: ice, replaces, outbound
Content-Type: application/sdp
Content-Length: 748

v=0
o=- 130154738700721458 2 IN IP4 172.31.11.64
s=-
t=0 0
a=extmap-allow-mixed
m=audio 41958 RTP/AVP 111 63 9 0 8 13 110 126
c=IN IP4 172.31.11.64
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=rtpmap:111 opus/48000/2
a=fmtp:111 useinbandfec=1; minptime=10
a=rtcp-fb:111 transport-cc
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=sendrecv
a=rtcp:41959

**Comment by xquanluu** [comment]
https://github.com/drachtio/drachtio-rtpengine-webrtcproxy/blob/master/lib/call-session.js#L120C9-L120C28

Please use all and drop header by -

example code.
 proxyRequestHeaders: [
          'all',
          '-X-Application-Sid',
        ],

**Comment by vdharashive** [comment]
thanks @xquanluu it worked
